﻿/*
Created: 13/02/2023
Modified: 20/02/2023
Model: Veterinaria_SOS
Database: MS SQL Server 2017
*/


-- Create tables section -------------------------------------------------

-- Table VT_PROPIETARIOS
CREATE DATABASE VeterinariaSOS
GO
USE VeterinariaSOS;
GO

IF OBJECT_ID('dbo.VT_PROPIETARIOS','U') IS NULL
BEGIN
    CREATE TABLE dbo.VT_PROPIETARIOS
    (
        PRO_ID                 INT IDENTITY(1,1) PRIMARY KEY,
        PRO_IDENTIFICACION     VARCHAR(15)  NOT NULL,
        PRO_PRIMER_NOMBRE      VARCHAR(25)  NOT NULL,
        PRO_SEGUNDO_NOMBRE     VARCHAR(25)  NOT NULL,
        PRO_PRIMER_APELLIDO    VARCHAR(25)  NOT NULL,
        PRO_SEGUNDO_APELLIDO   VARCHAR(25)  NOT NULL,
        PRO_TELEFONO           VARCHAR(8)   NOT NULL,
        PRO_CORREO             VARCHAR(150) NOT NULL,
        PRO_ADICIONADO_POR     VARCHAR(15)  NOT NULL,
        PRO_FECHA_ADICION      DATETIME     NOT NULL,
        PRO_MODIFICADO_POR     VARCHAR(15)  NULL,
        PRO_FECHA_MODIFICACION DATETIME     NULL
    );
END
GO

IF OBJECT_ID('dbo.VT_MASCOTAS','U') IS NULL
BEGIN
    CREATE TABLE dbo.VT_MASCOTAS
    (
        MAS_ID                 INT IDENTITY(1,1) PRIMARY KEY,
        MAS_NOMBRE             VARCHAR(15)  NOT NULL,
        MAS_FECHA_NACIMIENTO   DATE         NOT NULL,
        MAS_SEXO               VARCHAR(1)   NOT NULL,
        MAS_PESO               NUMERIC(5,2) NOT NULL,
        MAS_ALERGIAS           VARCHAR(150) NULL,
        MAS_PRO_ID             INT          NOT NULL,
        MAS_ADICIONADO_POR     VARCHAR(15)  NOT NULL,
        MAS_FECHA_ADICION      DATETIME     NOT NULL,
        MAS_MODIFICADO_POR     VARCHAR(15)  NULL,
        MAS_FECHA_MODIFICACION DATETIME     NULL
    );
END
GO

IF OBJECT_ID('dbo.VT_HOJA','U') IS NULL
BEGIN
    CREATE TABLE dbo.VT_HOJA
    (
        HOJ_ID                 INT IDENTITY(1,1) PRIMARY KEY,
        HOJ_FECHA_ATENCION     DATETIME     NOT NULL,
        HOJ_SINTOMAS           VARCHAR(150) NOT NULL,
        HOJ_DIAGNOSTICO        VARCHAR(150) NOT NULL,
        HOJ_TRATAMIENTO        VARCHAR(150) NOT NULL,
        HOJ_MAS_ID             INT          NOT NULL,
        HOJ_ADICIONADO_POR     VARCHAR(15)  NOT NULL,
        HOJ_FECHA_ADICION      DATETIME     NOT NULL,
        HOJ_MODIFICADO_POR     VARCHAR(15)  NULL,
        HOJ_FECHA_MODIFICACION DATETIME     NULL
    );
END
GO

IF OBJECT_ID('dbo.VT_USUARIOS','U') IS NULL
BEGIN
    CREATE TABLE dbo.VT_USUARIOS
    (
        USU_ID                 INT IDENTITY(1,1) PRIMARY KEY,
        USU_USUARIO            VARCHAR(15) NOT NULL,
        USU_CLAVE              VARCHAR(10) NOT NULL,
        USU_ESTADO             VARCHAR(1)  NOT NULL CONSTRAINT CK_CR_USUARIOS_ESTADO CHECK (USU_ESTADO IN ('A','I')),
        USU_ADICIONADO_POR     VARCHAR(15) NOT NULL,
        USU_FECHA_ADICION      DATETIME    NOT NULL,
        USU_MODIFICADO_POR     VARCHAR(15) NULL,
        USU_FECHA_MODIFICACION DATETIME    NULL
    );
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name='PRO_X_MAS')
    ALTER TABLE dbo.VT_MASCOTAS
    ADD CONSTRAINT PRO_X_MAS FOREIGN KEY (MAS_PRO_ID) REFERENCES dbo.VT_PROPIETARIOS(PRO_ID);
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name='MAS_X_HOJ')
    ALTER TABLE dbo.VT_HOJA
    ADD CONSTRAINT MAS_X_HOJ FOREIGN KEY (HOJ_MAS_ID) REFERENCES dbo.VT_MASCOTAS(MAS_ID);
GO

-- Seed mínimo
IF NOT EXISTS (SELECT 1 FROM dbo.VT_USUARIOS)
INSERT INTO dbo.VT_USUARIOS (USU_USUARIO,USU_CLAVE,USU_ESTADO,USU_ADICIONADO_POR,USU_FECHA_ADICION)
VALUES ('Allen','123','A','ADMIN',GETDATE());

